steps:

# Step 1 - Terraform Init
- name: hashicorp/terraform:1.6
  entrypoint: sh
  args:
    - "-c"
    - |
      terraform init
      terraform plan \
        -var="project_id=$PROJECT_ID" \
        -var="region=us-central1" \
        -var="zone=us-central1-a" \
        -out=tfplan

# Step 2 - Terraform Plan
- name: hashicorp/terraform:1.6
  entrypoint: sh
  args:
    - "-c"
    - |
      terraform plan -out=tfplan

# Step 3 - Terraform Apply
- name: hashicorp/terraform:1.6
  entrypoint: sh
  args:
    - "-c"
    - |
      terraform apply -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY

# all set