steps:

# Step 1 - Init
- name: hashicorp/terraform:1.6
  entrypoint: sh
  args:
    - "-c"
    - |
      terraform init

# Step 2 - Plan
- name: hashicorp/terraform:1.6
  entrypoint: sh
  args:
    - "-c"
    - |
      terraform plan \
        -var="project_id=$PROJECT_ID" \
        -var="region=us-central1" \
        -var="zone=us-central1-a" \
        -out=tfplan

# Step 3 - Apply
- name: hashicorp/terraform:1.6
  entrypoint: sh
  args:
    - "-c"
    - |
      terraform apply -auto-approve tfplan


options:
  logging: CLOUD_LOGGING_ONLY